### ISSUE TITLE
Incorrect Azure AI CLI steps for Mac OS 

### ISSUE THREAD

**Issue by mjaferDo** [robch/book-of-ai#1]
The installation steps mentioned for Mac OS on the following link for Azure AI CLI are incorrect.
https://thebookof.ai/install-ai-cli/
When I run the script it fails with the following error.

> dotnet is not installed.
Installing dotnet 8.0...
sudo: apt-get: command not found
awk: can't open file /etc/os-release
 source line number 1
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Unsupported distribution: 

It seems the "https://aka.ms/InstallAzureAICLIDeb" script is not meant for Mac OS.

Instead I installed the dotnet sdk using brew on Mac OS
`brew install --cask dotnet-sdk`

and then install using the steps provided in the [Azure AI CLI GitHub repo.](https://github.com/Azure/azure-ai-cli?tab=readme-ov-file#option-3-local-installation)
`dotnet tool install -g Azure.AI.CLI --prerelease`

**Comment by robch** [comment]
Fixed with https://github.com/robch/book-of-ai/commit/9f959733c42fdcdf97a8f7f72781ffe02c0a2e42

**Comment by robch** [comment]
Fixed with [commit 9f959733c42fdcdf97a8f7f72781ffe02c0a2e42](https://github.com/robch/book-of-ai/commit/9f959733c42fdcdf97a8f7f72781ffe02c0a2e42)
